describe('Create Account', () => {
    it('Weak Password', () => {
      cy.visit('https://magento.softwaretestingboard.com/customer/account/create/')
      cy.get('#firstname').type('Reza')
      cy.get('#lastname').type('Anjasmoro')
      cy.get('#email_address').type('reza@gmail.com')
      cy.get('#password').type('rezaanjas')
      cy.get('#password-confirmation').type('rezaanjas')
      cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
    })
    it('Strong Password', () => {
      cy.visit('https://magento.softwaretestingboard.com/customer/account/create/')
      cy.get('#firstname').type('Reza')
      cy.get('#lastname').type('Anjasmoro')
      cy.get('#email_address').type('reza8@gmail.com')
      cy.get('#password').type('Rezaanjas8')
      cy.get('#password-confirmation').type('Rezaanjas8')
      cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
    })
    it.only('Very Strong Password', () => {
      cy.visit('https://magento.softwaretestingboard.com/customer/account/create/')
      cy.get('#firstname').type('Reza')
      cy.get('#lastname').type('Anjasmoro')
      cy.get('#email_address').type('reza88@gmail.com')
      cy.get('#password').type('Rezaanjas8!')
      cy.get('#password-confirmation').type('Rezaanjas8!')
      cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
    })
  })